name: docker

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and push the docker image to ghcr.io
        run: |
          rustup update
          rustup target add x86_64-unknown-linux-musl
          cargo build --target x86_64-unknown-linux-musl --release
          echo $CR_PAT | docker login ghcr.io -u yasuyuky --password-stdin
          docker build . -t ghcr.io/yasuyuky/svgcard:latest
          docker push -a ghcr.io/yasuyuky/svgcard
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
